language: node_js
sudo: false
node_js:
  - 8
script:
  - npm i
  - npm run docs:build
  - cd ./docs_dist
  - git init
  - git add --all .
  - git commit -m "Travis CI Auto Builder"
  - git push --quiet --force https://$REPO_TOKEN@github.com/macacajs/NoSmoke.git master:gh-pages
  - cd ..
  - npm run lint
  - npm run test
after_script:
  - npm install coveralls@2 && cat ./coverage/lcov.info | coveralls
