---
# 1. Initialization option
desiredCapabilities:

  #Android Configuration
  #platformName: 'android'
  #isWaitActivity: true
  #activity: 'LoginActivity'
  #app: 'https://npmcdn.com/android-app-bootstrap@latest/android_app_bootstrap/build/outputs/apk/android_app_bootstrap-debug.apk'


#  Web Configuration
#  platformName: 'Desktop'
#  browserName: 'Electron'
#  url: 'https://macacajs.github.io'

#  iOS Configuration
  platformName: 'iOS'
  #sdkVersion: '10.3'
  #deviceName: 'iPhone 6 Plus'
  #app: 'https://npmcdn.com/ios-app-bootstrap@latest/build/ios-app-bootstrap.zip'
  #app: '/Users/icbc/Documents/macaca_files/issp.app'
  #bundleId: 'dev.com.icbc.dccb.issp'
  #bundleId: 'dev.com.icbc.customerIM'
  #bundleId: 'dev.com.icbc.Elife'
  #bundleId: 'dev.com.icbc.einvest'
  bundleId: 'com.apple.mobilesafari'
  udid: '79b970d47e23c9c5073dfcd4446320b169886f15' #iphone7 plus

#  Android Configuration
#  platformName: 'android'
#  isWaitActivity: true
#  activity: 'LoginActivity'
#  app: 'https://npmcdn.com/android-app-bootstrap@latest/android_app_bootstrap/build/outputs/apk/android_app_bootstrap-debug.apk'

# 2. Crawling option
crawlingConfig:
  platform: 'iOS'
  targetElements:
      loginAccount:
        actionType  : 2
        searchValue : 'please input username'
        #searchValue : '统一认证号'
        actionValue : ''
      loginPassword:
        actionType  : 2
        searchValue : 'please input password'
        #searchValue : '密码'
        actionValue : ''
      loginButton:
        actionType  : 1
        searchValue : 'Login'
        #searchValue : '登 录'
      alertConfirm:
        actionType  : 1
        searchValue : 'yes|确定|取消|无线局域网与蜂窝移动网络|好|允许'
  exclusivePattern: 'pushView|popView|cookie|userAgent:|Mozilla|cookie:|setTitle|Macaca Test Swipe API'
  clickTypes:
    - 'StaticText'
    - 'Button'
  editTypes:
    - 'TextField'
    - 'SecureTextField'
  horizontalScrollTypes:
    - 'PageIndicator'
  verticalScrollTypes:
    - 'ScrollView'
  tabBarTypes:
    - 'TabBar'
  exclusiveTypes:
    - 'NavigationBar'
  navigationBackKeyword:
    - '返回'
    - '取消'
...

# Web Configuration
#  platform: 'pc-web'
#  clickTypes:
#    - 'a'
#  editTypes:
#    - 'input'

#  # Android Configuration
#  platform: 'android'
#  targetElements:
#      loginAccount:
#        actionType  : 2
#        searchValue : 'please input username'
#        actionValue : '中文+Test+12345678'
#      loginPassword:
#        actionType  : 2
#        searchValue : 'please input password'
#        actionValue : '111111'
#      loginButton:
#        actionType  : 1
#        searchValue : 'Login'
#      alertConfirm:
#        actionType  : 1
#        searchValue : 'yes'
#  exclusivePattern: 'pushView/popView/cookie/userAgent:/Mozilla/cookie:/setTitle/Macaca Test Swipe API/'
#  clickTypes:
#    - 'android.widget.ImageView'
#    - 'android.widget.TextView'
#    - 'android.widget.Button'
#  editTypes:
#    - 'android.widget.EditText'
#  tabBarTypes:
#    - 'android.widget.TabWidget'

#  # iOS Configuration
#  platform: 'iOS'
#  targetElements:
#      loginAccount:
#        actionType  : 2
#        searchValue : 'please input username'
#        actionValue : '中文+Test+12345678'
#      loginPassword:
#        actionType  : 2
#        searchValue : 'please input password'
#        actionValue : '111111'
#      loginButton:
#        actionType  : 1
#        searchValue : 'Login'
#      alertConfirm:
#        actionType  : 1
#        searchValue : 'yes'
#  exclusivePattern: 'pushView/popView/cookie/userAgent:/Mozilla/cookie:/setTitle/Macaca Test Swipe API/'
#  clickTypes:
#    - 'StaticText'
#    - 'Button'
#  editTypes:
#    - 'TextField'
#    - 'SecureTextField'
#  horizontalScrollTypes:
#    - 'PageIndicator'
#  verticalScrollTypes:
#    - 'ScrollView'
#  tabBarTypes:
#    - 'TabBar'
#  exclusiveTypes:
#    - 'NavigationBar'
#  navigationBackKeyword:
#    - '返回'
#    - '取消'
